# Generated by Django 4.2 on 2025-04-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('transactions', '0002_alter_purchase_options_alter_purchase_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='store.item'),
        ),
    ]
