# Generated by Django 4.2.19 on 2025-04-23 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('address', models.JSONField(blank=True, help_text='Structured address data', null=True, verbose_name='Full Address')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('loyalty_points', models.PositiveIntegerField(default=0, verbose_name='Reward Points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Vendor Name')),
                ('slug', models.SlugField(blank=True, default='', help_text='URL-friendly version of the name', unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Contact Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Business Address')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Vendor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='', unique=True, verbose_name='Account ID')),
                ('profile_picture', imagekit.models.fields.ProcessedImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/%Y/%m/%d/')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Include country code (e.g. +1 555 123 4567)', max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='Preferred email for communications', max_length=150, null=True, verbose_name='Contact Email')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Last Name')),
                ('status', models.CharField(choices=[('INA', 'Inactive'), ('A', 'Active'), ('OL', 'On leave')], default='INA', max_length=3, verbose_name='Account Status')),
                ('role', models.CharField(blank=True, choices=[('OP', 'Operative'), ('EX', 'Executive'), ('AD', 'Admin')], max_length=2, null=True, verbose_name='System Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-status', 'first_name', 'last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'email'), name='unique_customer'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['status'], name='accounts_pr_status_de1539_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='accounts_pr_role_fae1f3_idx'),
        ),
    ]
