# Generated by Django 4.2 on 2025-04-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Account ID'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['slug'], name='accounts_pr_slug_ea9f2d_idx'),
        ),
    ]
