# Generated by Django 4.2 on 2025-04-27 16:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to='profile_pics/%Y/%m/%d/'),
        ),
    ]
