# Generated by Django 4.2 on 2025-04-30 11:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Include country code (e.g. +251 - -- -- -- --)', max_length=128, null=True, region='ET', verbose_name='Phone Number'),
        ),
    ]
