# Generated by Django 4.2.19 on 2025-04-23 15:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(max_length=256, verbose_name='Item Description')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Available Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Unit Price')),
                ('expiring_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Category')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Customer Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Delivery Location')),
                ('date', models.DateTimeField(verbose_name='Delivery Date')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Is Delivered')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item', verbose_name='Delivered Item')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['slug'], name='store_item_slug_8f3653_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='store_item_categor_a02714_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['item'], name='store_deliv_item_id_ab6cac_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['date'], name='store_deliv_date_0cd140_idx'),
        ),
    ]
