# Generated by Django 4.2 on 2025-05-02 19:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to='item_image/%Y/%m/%d/'),
        ),
    ]
