# Generated by Django 4.2.19 on 2025-04-23 15:41

import autoslug.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Automatically generated URL identifier', populate_from='date', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('institution_name', models.CharField(help_text='Name of the billed institution', max_length=100, verbose_name='Institution')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number with country code', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='Full physical address', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of charges', null=True)),
                ('payment_details', models.CharField(help_text='Payment method/reference details', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount due', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount (Ksh)')),
                ('status', models.CharField(choices=[('UN', 'Unpaid'), ('PA', 'Paid'), ('PR', 'Partially Paid')], default='UN', max_length=2, verbose_name='Payment Status')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['-date'],
            },
        ),
    ]
