# Generated by Django 4.2 on 2025-04-30 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount due', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount (ETB)'),
        ),
    ]
