# Generated by Django 4.2.19 on 2025-04-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Auto-generated URL identifier', unique=True),
        ),
    ]
